[package]
name = "tasks"
version = "0.1.0"
edition = "2021"
default-run = "tasks"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.1", features = ["derive"] }
