[package]
name = "indexing"
version = "0.1.0"
edition = "2021"
default-run = "indexing"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.1", features = ["derive"] }
serde_json = "1.0.81"
