--TELEVOTI(CodP, CodT, CodD, CodO, ModalitaVoto, NumeroVoti, SommaVoti, Incasso)
--PARTECIPANTE(CodP, Partecipante, CodC)
--TELESPETTATORI(CodT, FasciaEta, Sesso, Categoria, CodC)
--CITTA(CodC, Citta, Provincia, Regione)
--DATA(CodD, Data, GiornoSettimana, Anno, Conduttore)
--ORARIO(CodO, Orario, OraGiorno)

DROP TABLE TELEVOTI;
DROP TABLE PARTECIPANTE;
DROP TABLE TELESPETTATORI;
DROP TABLE CITTA;
DROP TABLE DATA;
DROP TABLE ORARIO;

CREATE TABLE TELEVOTI
(
	CodP NUMBER NOT NULL,
	CodT NUMBER NOT NULL,
	CodD NUMBER NOT NULL,
	CodO NUMBER NOT NULL,
	ModalitaVoto VARCHAR2(50) NOT NULL,
	NumeroVoti NUMBER NOT NULL,
	SommaVoti NUMBER NOT NULL,
	Incasso NUMBER NOT NULL,
	PRIMARY KEY(CodP, CodT, CodD, CodO, ModalitaVoto)
);

CREATE TABLE PARTECIPANTE
(
	CodP NUMBER NOT NULL,
	Partecipante VARCHAR2(50) NOT NULL,
	CodC NUMBER NOT NULL,
	PRIMARY KEY(CodP)
);

CREATE TABLE TELESPETTATORI
(
	CodT NUMBER NOT NULL,
	FasciaEta VARCHAR2(50) NOT NULL,
	Sesso VARCHAR2(50) NOT NULL,
	Categoria VARCHAR2(50) NOT NULL,
	CodC NUMBER NOT NULL,
	PRIMARY KEY(CodT)
);

CREATE TABLE CITTA
(
	CodC NUMBER NOT NULL,
	Citta VARCHAR2(50) NOT NULL,
	Provincia VARCHAR2(50) NOT NULL,
	Regione VARCHAR2(50) NOT NULL,
	PRIMARY KEY(CodC)
);

CREATE TABLE DATA
(
	CodD NUMBER NOT NULL,
	Data VARCHAR2(50) NOT NULL,
	GiornoSettimana VARCHAR2(50) NOT NULL,
	Anno VARCHAR2(50) NOT NULL,
	Conduttore VARCHAR2(50) NOT NULL,
	PRIMARY KEY(CodD)
);

CREATE TABLE ORARIO
(
	CodO NUMBER NOT NULL,
	Orario VARCHAR2(50) NOT NULL,
	OraGiorno VARCHAR2(50) NOT NULL,
	PRIMARY KEY(CodO)
);